### PR TITLE
Patches from Debian package

### PR DESCRIPTION
**Pull request by marvhh**
Hi,

i'm the current maintainer from the syrep package in Debian.
As me and the community commited some patches, I want to give them back to upstream.

### CODE REVIEW

**Comment by JonathonReinhart** [comment]
Hi @marvhh,

Wow, it seems that this is the only fork of `syrep` on GitHub! That explains how you found this forgotten fork :smile: 

This is not the official "upstream" of syrep. The official home of syrep is on Lennart's site: http://0pointer.de/lennart/projects/syrep/

This repo isn't even a real fork -- the SVN repository listed on that page is inaccessible. I reached out to @poettering back in 2019 about Syrep but didn't hear back. So I created this repo by [committing](https://github.com/JonathonReinhart/syrep/commits/master) each of the 9 release tarball on that page.

I no longer have any interest in syrep, and I'd prefer to just archive this repository, rather than have it become a pseudo-upstream.

I would suggest instead just maintaining this on Salsa, but it appears you've already done that :grinning:: https://salsa.debian.org/marv/syrep

**Comment by marvhh** [comment]
Hi @JonathonReinhart,

i tried to reach @poettering via email in 2009 until 2011 forwarding him the bug reports and fixes. I never received an answer from him. As the commits here on Github were displayed "coauthored" I thought maybe you guys are in contact and I give this PR a try.

As he is also not answering you, syrep is probably dead 💀

**Comment by JonathonReinhart** [comment]
> As the commits here on Github were displayed "coauthored" I thought maybe you guys are in contact and I give this PR a try.

Ah, nope. I just specified him as `--author` when I committed the releases. So they are not "coauthored"; but rather it says

> @poettering authored and @JonathonReinhart committed

As for this:
 
> As he is also not answering you, syrep is probably dead 💀

Yes, I agree.

That's why, if you want to continue maintaining it for Debian, I think Salsa is as good a home as any.

Is it okay if we close this PR and I archive this repo?

**Comment by marvhh** [comment]
[...]
> That's why, if you want to continue maintaining it for Debian, I think Salsa is as good a home as any.
> 
> Is it okay if we close this PR and I archive this repo?

I think the same way, your solution is fine, let's do this.
Have a good one!

**Comment by JonathonReinhart** [comment]
Cheers!

**Pull request closed without merging**
